"""init

Revision ID: e9bfb22efa19
Revises: 
Create Date: 2026-06-28 00:29:38.949131
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9bfb22efa19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('confirmed_cause', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_created_at'), 'findings', ['created_at'], unique=False)
    op.create_index(op.f('ix_findings_store_id'), 'findings', ['store_id'], unique=False)
    op.create_table('inventory_level_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_store_sku_time', 'inventory_level_events', ['store_id', 'sku', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_level_events_occurred_at'), 'inventory_level_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_level_events_sku'), 'inventory_level_events', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_level_events_store_id'), 'inventory_level_events', ['store_id'], unique=False)
    op.create_table('metric_timeseries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'metric', 'day', name='uq_metric_store_day')
    )
    op.create_index(op.f('ix_metric_timeseries_day'), 'metric_timeseries', ['day'], unique=False)
    op.create_index(op.f('ix_metric_timeseries_metric'), 'metric_timeseries', ['metric'], unique=False)
    op.create_index(op.f('ix_metric_timeseries_store_id'), 'metric_timeseries', ['store_id'], unique=False)
    op.create_index(op.f('ix_metric_timeseries_weekday'), 'metric_timeseries', ['weekday'], unique=False)
    op.create_table('order_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('order_ref', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at_store', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_line_items_created_at_store'), 'order_line_items', ['created_at_store'], unique=False)
    op.create_index(op.f('ix_order_line_items_sku'), 'order_line_items', ['sku'], unique=False)
    op.create_index(op.f('ix_order_line_items_store_id'), 'order_line_items', ['store_id'], unique=False)
    op.create_table('order_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('order_ref', sa.String(), nullable=False),
    sa.Column('created_at_store', sa.DateTime(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('financial_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'order_ref', name='uq_order_store_ref')
    )
    op.create_index(op.f('ix_order_snapshots_created_at_store'), 'order_snapshots', ['created_at_store'], unique=False)
    op.create_index(op.f('ix_order_snapshots_store_id'), 'order_snapshots', ['store_id'], unique=False)
    op.create_table('stores',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('variant_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('inventory_item_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'inventory_item_id', name='uq_variant_store_item')
    )
    op.create_index(op.f('ix_variant_map_inventory_item_id'), 'variant_map', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_variant_map_store_id'), 'variant_map', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_map_store_id'), table_name='variant_map')
    op.drop_index(op.f('ix_variant_map_inventory_item_id'), table_name='variant_map')
    op.drop_table('variant_map')
    op.drop_table('stores')
    op.drop_index(op.f('ix_order_snapshots_store_id'), table_name='order_snapshots')
    op.drop_index(op.f('ix_order_snapshots_created_at_store'), table_name='order_snapshots')
    op.drop_table('order_snapshots')
    op.drop_index(op.f('ix_order_line_items_store_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_sku'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_created_at_store'), table_name='order_line_items')
    op.drop_table('order_line_items')
    op.drop_index(op.f('ix_metric_timeseries_weekday'), table_name='metric_timeseries')
    op.drop_index(op.f('ix_metric_timeseries_store_id'), table_name='metric_timeseries')
    op.drop_index(op.f('ix_metric_timeseries_metric'), table_name='metric_timeseries')
    op.drop_index(op.f('ix_metric_timeseries_day'), table_name='metric_timeseries')
    op.drop_table('metric_timeseries')
    op.drop_index(op.f('ix_inventory_level_events_store_id'), table_name='inventory_level_events')
    op.drop_index(op.f('ix_inventory_level_events_sku'), table_name='inventory_level_events')
    op.drop_index(op.f('ix_inventory_level_events_occurred_at'), table_name='inventory_level_events')
    op.drop_index('ix_inv_store_sku_time', table_name='inventory_level_events')
    op.drop_table('inventory_level_events')
    op.drop_index(op.f('ix_findings_store_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_created_at'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
